### ISSUE TITLE
Not showing complete sets

### ISSUE THREAD

**Issue by mdemuria** [CLOUGH/poe-recipe#2]
Hello, I downloaded and tried your application however it seems to not be showing complete sets, despite having complete sets. Its reading correctly what items I have in my stash but for some reason is not categorizing them as a "set". Picture attached to show what I mean.
![Capture](https://user-images.githubusercontent.com/77870354/105568311-eeee2d80-5cfd-11eb-94e4-3042f7596baa.PNG)

**Comment by CLOUGH** [comment]
I saw that you closed the issue yourself. I think you realize you had the weapons selected why it was just highlight all the weapons you had. 

I'm put in some extra effort with ironing out all of the UI issues.

Thanks for the feedback. I really appreciate the effort with trying to identify and raise the issues.
